import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  Link,
  Button,
} from "@nextui-org/react";

import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu"

// TODO: Switch from NextUI to Shadcn

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navbar>
          <NavbarContent>
            <NavbarItem>
              <Link href="/">
                <NavbarBrand>Home</NavbarBrand>
              </Link>
            </NavbarItem>
            <NavbarItem>
              <Link href="/games">
                <span>Games</span>
              </Link>
            </NavbarItem>
            <NavbarItem>
              <Link href="/notes">
                <span>Notes</span>
              </Link>
            </NavbarItem>
          </NavbarContent>
        </Navbar>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
